name: "node.js CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2 # Use the latest version of setup-node
        with:
          node-version: ${{ matrix.node-version }}
          
      # Backend dependencies installation
      - name: Install Backend Dependencies
        run: |
          npm ci # Use npm ci for a more consistent and faster installation when using a package-lock.json
          npm install express
      
      # Frontend dependencies installation and build
      - name: Install Frontend Dependencies and Build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
        env:
          CI: false
          
      # PM2 and Nginx operations
      - name: Manage PM2 and Nginx
        run: |
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart
