name: "node.js CI"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run:
        working-directory: ./
      - run: npm install
      - run: npm install express
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
      - run: pm2 stop 0
      - run: pm2 start 0
      - run: pm2 save
      - run: sudo service nginx restart
